apiVersion: apps/v1
kind: Deployment
metadata:
  name: housing-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: housing-model
  template:
    metadata:
      labels:
        app: housing-model
    spec:
      containers:
      - name: housing-model
        image: housing-model:1.0.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: housing-model-pv
            mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
        - name: housing-model-pv
          persistentVolumeClaim:
            claimName: housing-model-pvc