apiVersion: v1
kind: PersistentVolume
metadata:
  name: housing-model-pv
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: Directory
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: housing-model-pvc
spec:
  volumeName: housing-model-pv
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
